services:
  - type: web
    name: uptime-kuma
    envVars: docker
      -key: PORT
       value: 3001
    repo: https://github.com/Nebulosa-Cat/uptime-kuma
    region: oregon
    plan: starter
    branch: master
    rootDir: uptime-kuma:/app/data
    healthCheckPath: /
